package Authors;
// Generated Oct 29, 2016 3:31:08 AM by Hibernate Tools 4.3.1



/**
 * Authors generated by hbm2java
 */
public class Authors  implements java.io.Serializable {


     private String authorId;
     private String name;

    public Authors() {
    }

	
    public Authors(String authorId) {
        this.authorId = authorId;
    }
    public Authors(String authorId, String name) {
       this.authorId = authorId;
       this.name = name;
    }
   
    public String getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


