package Authors;
// Generated Oct 29, 2016 3:31:08 AM by Hibernate Tools 4.3.1



/**
 * Booksauthors generated by hbm2java
 */
public class Booksauthors  implements java.io.Serializable {


     private BooksauthorsId id;
     private Integer seqNo;

    public Booksauthors() {
    }

	
    public Booksauthors(BooksauthorsId id) {
        this.id = id;
    }
    public Booksauthors(BooksauthorsId id, Integer seqNo) {
       this.id = id;
       this.seqNo = seqNo;
    }
   
    public BooksauthorsId getId() {
        return this.id;
    }
    
    public void setId(BooksauthorsId id) {
        this.id = id;
    }
    public Integer getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }




}


